CREATE DATABASE saham_db;
USE saham_db;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100),
  email VARCHAR(100) UNIQUE,
  password VARCHAR(255)
);

CREATE TABLE absen (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  type ENUM('IN','OUT'),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
