pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                dir('absen-app') {
                    sh 'docker build -t absen-app:latest .'
                }
            }
        }

        stage('Deploy Container') {
            steps {
                sh '''
                docker rm -f absen-app || true
                docker run -d --name absen-app -p 8084:80 absen-app:latest
                '''
            }
        }
    }
}
